### ISSUE TITLE
求助

### ISSUE THREAD

**Issue by Xuanxuan-Tian** [yuanrongxi/razor#10]
![image](https://user-images.githubusercontent.com/28618492/49350802-6d854c80-f6eb-11e8-8257-c4e0f87c4bf8.png)
你好，在vs2013上编译的时候遇到这个问题，请问是什么原因，刚开始学习，还望大神指点一下，问题比较低级，还望大神谅解

**Comment by yuanrongxi** [comment]
你空格下这个feedback再进行编译就OK了
