### ISSUE TITLE
链接错误---

### ISSUE THREAD

**Issue by zark19890929** [yuanrongxi/razor#11]
博主，本人菜鸟一枚，编译碰到了这个问题，但是其实在代码跟踪又能够跟踪到具体的实现，麻烦指点一下，谢谢!

环境VS2013

错误	43	error LNK2019: 无法解析的外部符号 _cc_feedback_adapter_init，该符号在函数 _sender_cc_create 中被引用	D:\work\CongestionControl\razor\sim_test\echo\razor.lib(sender_congestion_controller.obj)	echo

错误	44	error LNK2019: 无法解析的外部符号 _cc_feedback_adapter_destroy，该符号在函数 _sender_cc_destroy 中被引用	D:\work\CongestionControl\razor\sim_test\echo\razor.lib(sender_congestion_controller.obj)	echo

错误	46	error LNK2019: 无法解析的外部符号 _cc_feedback_on_feedback，该符号在函数 _sender_on_feedback 中被引用	D:\work\CongestionControl\razor\sim_test\echo\razor.lib(sender_congestion_controller.obj)	echo

**Comment by zark19890929** [comment]
解决了，很奇怪，把这些头文件和c文件删除引用然后再重新添加进来就可以了.

**Comment by yuanrongxi** [comment]
是这样的
