### ISSUE TITLE
这个项目的目标是什么

### ISSUE THREAD

**Issue by DyncEric** [yuanrongxi/razor#17]
想知道这个项目只是做测试各种流控算法使用，还是说未来可以达到商用级别，做一个稳定高效的音视频传输库使用

**Comment by yuanrongxi** [comment]
暂时没有做成商业库的打算，只是提供一个视频传输了流控算法模块，不涉及到传输的具体协议

**Comment by DyncEric** [comment]
了解，谢谢啦
