### ISSUE TITLE
关于测试结果？

### ISSUE THREAD

**Issue by Aguaimama** [yuanrongxi/razor#20]
请教一下袁老师，用测试的sender和receiver进行测试，gcc和bbr这两种拥塞控制算法，发现gcc基本上一直线性增长到3000kb/s，bbr测试先增后减再增加到更高然后再减少（看着是探测带宽的一个过程）再最后趋于稳定，但是bbr的速度最终稳定的速度大概只有400-500kb/s。请问这是正常结果吗？觉得bbr的好像不对？

**Comment by ucasxuxm** [comment]
确实有这个疑惑，不知道什么原因导致的？

**Comment by ucasxuxm** [comment]
有一个想法：是不是每个数据包都需要相应的ACK包进行回应，增加了网络中包的数量，而对于gcc，ack包的数量并不会很多；

**Comment by yuanrongxi** [comment]
要看设置的最大码率上限，我记得测试程序设置的是300KB最大上限，不知道你是否改动过测试程序

**Comment by yuanrongxi** [comment]
应该是BBR批量确认造成的问题，我把批量确认做一下优化看看
