### ISSUE TITLE
razor sender被限制带宽后，以及放开限制后的行为

### ISSUE THREAD

**Issue by adcen0107** [yuanrongxi/razor#29]
袁老师，您好。我在局域网两个windowsPC里使用sim receiver, sim sender相互发包，中间串联一个网络损伤仪。正常不限制情况下，remb或BBR算法下，sim sender可以跑到6M且比较稳定，当我限制一个方向的带宽到2M时，sim_sender会快速落到2M左右，但是统计显示会有很大的丢包率（60到100之间），然后sim sender发送带宽和速率进一步下降，最终停留在150K左右。当我放开带宽时，此时sim sender并未恢复，还是保持在150K。 所以，我想请教：remb或BBR是不是能够出当前可用带宽值，感觉我们的sim test是可以调整发包速率让其等于带宽，从而稳定，但是测试结果为什么是这样的呢？
 同时，我发现GCC找到可用带宽然后稳定下来的能力更强一些，但是，三种算法（GCC, BBR, REMB）都不能在限制取消后恢复发送速率。想问一下袁老师，从razor的原理上看，是不是本身也不支持这样的带宽恢复功能呢？

**Comment by yuanrongxi** [comment]
应该是支持恢复功能的，不知道网损仪是什么原理，限流我用winshaper是可以恢复的，你获取下新的代码试试看看？

**Comment by adcen0107** [comment]
是我之前sim_connect()里面没有将padding置1，重新置1后编译再测试，带宽限制放开后，码率是可以恢复的。
我对比9月的版本和10月版本，发现了一个不同，我个人觉得9月版本似乎更合理些。

**Comment by adcen0107** [comment]
不好意思，是我之前测试环境问题，确实可以恢复，也很稳定！

**Comment by adcen0107** [comment]
再次请教袁老师，如果I帧比P帧大几倍，如果按照Razor的发包方式（pacing平滑），理论上I帧所在那秒就会产生延时；如果不平滑，强行把I帧在一定时间范围内把它发出去，就会触发拥塞。总的来说，编码器不能保证很稳定的码率时，结合拥塞控制，您们会怎么解决这个问题呢？
