### ISSUE TITLE
Razor发送特大I帧

### ISSUE THREAD

**Issue by adcen0107** [yuanrongxi/razor#31]
袁老师，您好！想请教一下，如果I帧比P帧大几倍，按照Razor的发包方式（pacing平滑），理论上I帧所在那秒就会产生延时；如果不平滑，强行把I帧在一定时间范围内把它发出去，就会触发拥塞。总的来说，编码器不能保证很稳定的码率时，结合拥塞控制，您有什么好的思路解决这个问题吗？

**Comment by yuanrongxi** [comment]
一般拥塞控制有PADDING机制，可以去结合这块来试试。
