### ISSUE TITLE
sim_recever与sim_sender的编译问题

### ISSUE THREAD

**Issue by wohainianqing** [yuanrongxi/razor#33]
**recever上编译出现问题：**
1>razor.lib(sender_congestion_controller.obj) : error LNK2019: 无法解析的外部符号 _cc_feedback_adapter_init，该符号在函数 _sender_cc_create 中被引用
1>razor.lib(sender_congestion_controller.obj) : error LNK2019: 无法解析的外部符号 _cc_feedback_adapter_destroy，该符号在函数 _sender_cc_destroy 中被引用
1>razor.lib(sender_congestion_controller.obj) : error LNK2019: 无法解析的外部符号 _cc_feedback_add_packet，该符号在函数 _sender_on_send_packet 中被引用
1>razor.lib(sender_congestion_controller.obj) : error LNK2019: 无法解析的外部符号 _cc_feedback_on_feedback，该符号在函数 _sender_on_feedback 中被引用
1>G:\码率自适应\razor-master\razor-master\sim_test\sim_receiver\Debug\sim_receiver.exe : fatal error LNK1120: 4 个无法解析的外部命令
**sender：**
sim_connect（）函数不接受三个参数，是否要传入六个参数
请问老师该怎么解决呀？

**Comment by yuanrongxi** [comment]
在cc_feedback_add_packet实现文件中空格一下，这块可能是2013上编译环境问题
