### ISSUE TITLE
请教一下两个编译的小问题

### ISSUE THREAD

**Issue by wohainianqing** [yuanrongxi/razor#34]
想请教一下各位大佬
1、在Linux下运行relay之前是不是也要编译razor下的project文件呀？
2、if (sim_connect(1000, "192.168.1.200", 6009) != 0){
	    printf("sim connect failed!\n");
	    goto err;
sim_connect设定好像是需要传入六个参数，这样修改好像会报错，请问可以怎么改呀？

**Comment by yuanrongxi** [comment]
relay只要直接在目录下Make就行了
sim_connect，第4个参数是指定拥塞控制算法类型的，第5个参数是设置要不要PADDING,最后一个参数是指定要不要启用FEC的标识。

**Comment by wohainianqing** [comment]
请问袁老师这句话“但需要将common目录文件”是什么意思啊？

**Comment by yuanrongxi** [comment]
> 请问袁老师这句话“但需要将common目录文件”是什么意思啊？

你去看relay下C文件的include

**Comment by wohainianqing** [comment]
请问linux下运行sim sender和sim receiver的话，要将工程文件转化为makefile文件再进行编译吗？
