### ISSUE TITLE
关于razor中fec的性能指标

### ISSUE THREAD

**Issue by adcen0107** [yuanrongxi/razor#39]
袁老师，您好！请问razor中fec比较适用的场景是什么呢？再就是fec在某些测试场景下的性能指标是怎么样的呢？

**Comment by yuanrongxi** [comment]
FEC在随机丢包的网络状态下使用的，如果是拥塞丢包和限流丢包，FEC作用不大，Razor的FEC在随机丢包模式下可以抗丢包30%。

**Comment by adcen0107** [comment]
明白了，谢谢袁老师！
