### ISSUE TITLE
test_pacer_queue执行就崩溃

### ISSUE THREAD

**Issue by sudokuhk** [yuanrongxi/razor#4]
`commit 953568159c3034363f4bf69a4ad9a27755f05752
Author: rongxi.yuan <rongxi.yuan@wenba100.com>
Date:   Fri Aug 17 11:01:53 2018 +0800
`

这个版本，编译出来的test程序，test_pacer_queue，代码有问题。
`pacer_queue_sent(&que, pos);`

传入的pos是int，需要的是packet_event_t *

**Comment by yuanrongxi** [comment]
最近我把这个接口改了，测试用例还没有来及改
