### ISSUE TITLE
这是不是一个书写错误

### ISSUE THREAD

**Issue by adcen0107** [yuanrongxi/razor#40]
袁老师，trendline.c文件中。
void trendline_update(trendline_estimator_t* est, double recv_delta_ms, double send_delta_ms, int64_t arrival_ts)
{
	double delta_ms = recv_delta_ms - send_delta_ms;
	delay_hist_t* hist; 

	est->num_of_deltas++;
	if (est->num_of_deltas > TRENDLINE_MAX_COUNT)
		est->num_of_deltas = est->num_of_deltas;    //这一行！
      ……
      ……
}
上面标的那一行是不是应该为est->num_of_deltas = TRENDLINE_MAX_COUNT，我看卡尔曼滤波中就是赋值了TRENDLINE_MAX_COUNT ？

**Comment by yuanrongxi** [comment]
是的，是问题

**Comment by yuanrongxi** [comment]
看你一直研究Razor,能加个联系方式吗？

**Comment by adcen0107** [comment]
好的，非常荣幸，cw981925@163.com

**Comment by yuanrongxi** [comment]
有微信吗？

**Comment by adcen0107** [comment]
这个：18520531887

**Comment by adcen0107** [comment]
袁老师，您微信搜上面的手机号就可以加的！

**Comment by adcen0107** [comment]
袁老师，这里是不是也有个书写错误呢？
static sim_frame_cache_t* open_real_video_cache(sim_session_t* s)
{
	sim_frame_cache_t* cache = calloc(1, sizeof(sim_frame_cache_t));
	cache->wait_timer = s->rtt + 2 * s->rtt_var;
	cache->state = buffer_waiting;
	cache->min_seq = 0;
	cache->frame_timer = 100;
	cache->f = 1.0f;
	cache->size = CACHE_SIZE;
	cache->frames = calloc(cache->size, sizeof(sim_frame_cache_t));   //这一行。

	cache->discard_loss = skiplist_create(idu32_compare, NULL, NULL);
	return cache;
}
是不是应该修改为 cache->frames = calloc(cache->size, sizeof(sim_frame_t)); 呢？
袁老师，方便加个您的微信不？我的微信：18520531887

**Comment by yuanrongxi** [comment]
> 袁老师，这里是不是也有个书写错误呢？
> static sim_frame_cache_t* open_real_video_cache(sim_session_t* s)
> {
> sim_frame_cache_t* cache = calloc(1, sizeof(sim_frame_cache_t));
> cache->wait_timer = s->rtt + 2 * s->rtt_var;
> cache->state = buffer_waiting;
> cache->min_seq = 0;
> cache->frame_timer = 100;
> cache->f = 1.0f;
> cache->size = CACHE_SIZE;
> cache->frames = calloc(cache->size, sizeof(sim_frame_cache_t)); //这一行。
> 
> ```
> cache->discard_loss = skiplist_create(idu32_compare, NULL, NULL);
> return cache;
> ```
> 
> }
> 是不是应该修改为 cache->frames = calloc(cache->size, sizeof(sim_frame_t)); 呢？
> 袁老师，方便加个您的微信不？我的微信：18520531887

这行是个问题，也是笔误，这样会造成内存多开辟
