### ISSUE TITLE
为什么设置丢包率为1呢？

### ISSUE THREAD

**Issue by chenhongquan** [yuanrongxi/razor#41]
袁老师您好：
请问为什么在文件sim_sender.c的函数sim_send_packet中，当padding == 1的时候，在发送完padding包之后，为什么要把丢包率设置为1呢？
就是这段代码：
if(s->loss_fraction == 0)
   s->loss_fraction = 1;

谢谢

**Comment by yuanrongxi** [comment]
为了启动FEC，因为PADDING是补发数据，如果用FEC填充，这样还能保证随机丢包的情况下通过FEC恢复，也达到了PADDING的效果.
