### ISSUE TITLE
关于接收缓冲区的播放问题

### ISSUE THREAD

**Issue by chenhongquan** [yuanrongxi/razor#42]
袁老师你好：
对于sim_frame_cache_t里面的几个时戳字段区分不怎么清楚，也就是play_frame_ts, max_ts, frame_ts, play_ts，能解释一下各自的用途和使用方法吗？另外，这个real_video_cache_sync_timestamp的作用也不明白，其中用到的c->f这个系数有什么说法吗？谢谢，麻烦了！

**Comment by yuanrongxi** [comment]
play_frame_ts max_ts frame_ts play_ts,是播放的相对时间戳和绝对时间戳，real_video_cache_sync_timestamp这个函数是根据网络报文中的相对时间戳和本地时钟绝对时间戳进行的时间同步，来决定该不该播放视频帧数据。f是根据网络和cache状态决定是否要加快和放慢播放的参数。

**Comment by chenhongquan** [comment]
谢谢
