### ISSUE TITLE
echo的输出日志问题

### ISSUE THREAD

**Issue by wohainianqing** [yuanrongxi/razor#43]
袁老师你好：
对于echo测试程序输出的日志中，send bandwidth = 141kb/s, recv bandwidth = 82kb/s, video rate = 88kb/s，不过利用带宽测试工具测试得到的值这边的单位好像应该是kB/s，想问下echo测试输出的单位是否是kB/s。麻烦了！

**Comment by yuanrongxi** [comment]
是以字节文单位的计数

**Comment by wohainianqing** [comment]
谢谢！
