### ISSUE TITLE
nack状态值与接收码率

### ISSUE THREAD

**Issue by wohainianqing** [yuanrongxi/razor#45]
请问袁老师razor里边nack的状态值和接收码率是怎么定义的，麻烦了！

**Comment by yuanrongxi** [comment]
nack是描述丢包的，每一个包在进行nack的时候有一定的条件出发，例如RTT限制、次数限制、频率限制。NACK会带来额外的发送带宽，这个带宽和FEC、新产生的视频数据共同分享CC预估出来的带宽，我只是做的比较简单，如果比较合理的需要用类似贝叶斯方式进行分配，其实是一个调参的事情，比较难量化。
