### ISSUE TITLE
在丢包环境下target_rate估不上去

### ISSUE THREAD

**Issue by carlcc** [yuanrongxi/razor#51]
袁老师好，我在私有协议中集成razor以后测试bbr，发现在丢包网络下target_rate估不上去。

我用tc设置的网络，发送方向模拟30%丢包10M带宽。

```bash
sudo tcset --direction outgoing  --loss 30% wlp0s20f3 --rate 10Mbps
```

![image](https://user-images.githubusercontent.com/12776190/130190136-556fd732-5941-41e9-9bb0-75403bd92ca4.png)

第一行是razor在razor_sender_create中传入的回调函数中返回的bitrate
第二行是我统计的实际送入udp socket的速率。

为什么会出现这种情况，按照我的理解，bbr应该对丢包不敏感，不应该出现估计带宽低于实际发送带宽的情况吧？

提前感谢袁老师！

**Comment by carlcc** [comment]
仔细想想，razor估计的是实际数据成功送达的速率或者取个名字叫`有效带宽`吧？它是刨去了丢失数据以后的带宽估计？

所以正确的方法应该是 totalSendBw * (1-lossRate) 和 estimatedBw 比较？

**Comment by yuanrongxi** [comment]
bbr论文中丢包率超过20%码率是极具下降的，这和BBR的算法有关系，可以去看一下BBR论文
