### ISSUE TITLE
BBR代码里面RTT计算疑问

### ISSUE THREAD

**Issue by DyncEric** [yuanrongxi/razor#54]
接收端bbr_receive_on_received()函数中如下代码
if (skiplist_size(cc->cache) >= 2)
{发送Feedback}
每两个包回一次Feedback，信令传输成本是不是有点高

**Comment by yuanrongxi** [comment]
Razor原本是考虑点对点的传输，为了更快反馈，所以设置了2，如果考虑应用到服务端，需要做对应的优化，我提了一个PR版本。
