### ISSUE TITLE
windowed_filter.c的实现是不是有问题？

### ISSUE THREAD

**Issue by sudokuhk** [yuanrongxi/razor#6]
windowed_filter.c的实现是不是有问题，我参照linux内核的win_minmax实现，和你一样的单元测试样例，但是输出不一样？
你的init_min_filter的输出是：
20
40
50
linux内核的算法输出是：
20
30
50

你的init_max_filter的输出是：
900 
700
600
linux内核的输出是：
900
800
700

附上测试代码：

[win_minmax.h.txt](https://github.com/yuanrongxi/razor/files/2318051/win_minmax.h.txt)
[win_minmax.c.txt](https://github.com/yuanrongxi/razor/files/2318054/win_minmax.c.txt)
[test.c.txt](https://github.com/yuanrongxi/razor/files/2318057/test.c.txt)

**Comment by yuanrongxi** [comment]
我这个是根据chrome中QUIC的实现的测试用来判定的,在QUIC的windowed_filter_test.cc中测试用例是这样写：
void InitializeMaxFilter() {
    QuicTime now = QuicTime::Zero();
    QuicBandwidth bw_sample = QuicBandwidth::FromBitsPerSecond(1000);
    for (int i = 0; i < 5; ++i) {
      windowed_max_bw_.Update(bw_sample, now);
      VLOG(1) << "i: " << i << " sample: " << bw_sample.ToBitsPerSecond()
              << " maxs: "
              << " " << windowed_max_bw_.GetBest().ToBitsPerSecond() << " "
              << windowed_max_bw_.GetSecondBest().ToBitsPerSecond() << " "
              << windowed_max_bw_.GetThirdBest().ToBitsPerSecond();
      now = now + QuicTime::Delta::FromMilliseconds(25);
      bw_sample = bw_sample - QuicBandwidth::FromBitsPerSecond(100);
    }
    EXPECT_EQ(QuicBandwidth::FromBitsPerSecond(900),
              windowed_max_bw_.GetBest());
    EXPECT_EQ(QuicBandwidth::FromBitsPerSecond(700),
              windowed_max_bw_.GetSecondBest());
    EXPECT_EQ(QuicBandwidth::FromBitsPerSecond(600),
              windowed_max_bw_.GetThirdBest());
  }
