### ISSUE TITLE
Razor的改造标准化，为Janus标准WebRTC的RTCP TWCC集成Razor GCC算法极大地缩短项目周期

### ISSUE THREAD

**Issue by LiuAriel** [yuanrongxi/razor#61]
原本打算将WebRTC的代码转译为C语言版本的GCC算法，并在此过程中查阅了大量相关的资料和博客。最后我决定直接使用Razor进行改造。在这个过程中，把所有的Git提交代码都拉取下来，花费了半个月的时间从零开始按照Razor的思路编写代码，并且完全理解了整个流程。此外也纠正了以前不理解或理解错误的部分，才开始动工改造。

首先，Razor中的GCC算法与2017年底的WebRTC的GCC版本相比，以及与当前最新的WebRTC的GCC版本相比，其核心算法并无太大改动；

其次，GCC被移植为C代码，这使得它能够方便地接入嵌入式设备和Janus服务，特别是对于嵌入式设备来说；

此外，微信公众号上分享的一篇GCC算法介绍文章，内容十分通俗易懂，关键点都很明确；

然而，唯一的美中不足是padding尚未实现，这需要自己去翻译和补充，哈哈。

感谢开源贡献。

**Comment by yuanrongxi** [comment]
good lucky
