### ISSUE TITLE
发送端和接收端直接通信输出的日志中，knb/s应该改写为kbp/s，但我没看到在哪个文件里修改输出的日志？

### ISSUE THREAD

**Issue by Jadaeu** [yuanrongxi/razor#63]
![image](https://github.com/yuanrongxi/razor/assets/105416501/a1956297-f4ba-4053-a415-df54993f0931)

**Comment by Jadaeu** [comment]
求好心大佬请教一下！

**Comment by yuanrongxi** [comment]
fix
