### ISSUE TITLE
测试bbr的瓶颈带宽探测性能时遇到问题，探测的带宽波动为什么会特别大？

### ISSUE THREAD

**Issue by Jadaeu** [yuanrongxi/razor#66]
由于bbr能探测出链路瓶颈带宽，所以想着测试一下bbr在弱网环境下的带宽探测性能，因此我将下面这段信息打印出来，红圈内就是bbr估计的带宽。
![image](https://github.com/yuanrongxi/razor/assets/105416501/bc84c58a-6998-442d-a377-8fb639d39619)
我利用netlimiter将本地网络限制到1Mbps（125KB/s），本地电脑向远程主机发送帧数据，探测到的带宽变化图如下图所示：
![image](https://github.com/yuanrongxi/razor/assets/105416501/00dbd023-c2e2-4024-8c11-54ed2489abb8)
想了好久，实在不明白探测到的瓶颈带宽波动范围会这么大。
之后看了看下面代码是如何估计带宽的
![image](https://github.com/yuanrongxi/razor/assets/105416501/790c14d4-f334-408d-a288-4e340fc66b09)
请问这块代码是作者原创的吗？不太理解这段代码。

**Comment by yuanrongxi** [comment]
是chrome里面的QUIC的代码，就是获取时间窗口中的最大排序码率。

**Comment by Jadaeu** [comment]
> 是chrome里面的QUIC的代码，就是获取时间窗口中的最大排序码率。

好的。还有一个问题，在第一个图中，为什么当congestion_window < bbr->min_congestion_window时，打印调试信息呢？不应该是当congestion_window < bbr->min_congestion_window || congestion_window > bbr->min_congestion_window时，都需要打印调试信息吗？
