### ISSUE TITLE
性能测试报告

### ISSUE THREAD

**Issue by xjsXjtu** [yuanrongxi/razor#7]
我有一个小小的想法。不知道作者有没有相关的性能测试报告，如带宽评估的准确性，收敛速度（包括大到小，小到大），以及与其他TCP、UDP流的竞争等。

我觉得如果有这样的报告的话，应该会有更多的人集成这个standalone的CC，进一步会有更多的人参与到仓库的开发中来。

**Comment by sudokuhk** [comment]
我也想过这个问题。目前正在看webrtc的代码，顺便对比下这个仓库的代码和webrtc

**Comment by sonyangchang** [comment]
https://github.com/sonyangchang/rmcat-ns3 ，在仿真情况下，和原版的webrtc差不多表现。

**Comment by yuanrongxi** [comment]
性能上和webRTC差不多，整个工程是移植webRTC的算法，我在GCC上改进了10%丢包限制的问题,BBR方面我做了webRTC上还未实现的码率调整策略，webRTC中的BBR还处于测试阶段。

**Comment by yuanrongxi** [comment]
我们已经做了压测和对比测试，在DOC目录下有测试的数据对比图。

**Comment by adcen0107** [comment]
请教一下各位：我使用了nkcubert forked的那一版Razor（d5a3890 2018），按照Doc文档使用网损仪16KB队列，限制250带宽，发送速率只跑到30kb/s，没有文档中显示的那样250kb/s左右。
是不是我的使用方法有问题？
